### ISSUE TITLE
Setup Database

### ISSUE THREAD

**Issue by Derek-Frevel** [CMPUT301W23T4/APPvengers#35]
Create a firebase database

- [x] Database created on google firebase
- [x] Database linked to the project
- [x] Database class can write to the firebase 
- [x] Database class can read from the firebase

**Comment by wangshuxie** [comment]
already create data base and connect it.

**Comment by charvidhamija** [comment]
need to add userprofile data to database

**Comment by charvidhamija** [comment]
done
